# yolo_dataset.yaml
path: datasets/my_dataset
train: images/train
val: images/val
names:
  0: construction helmet
  1: construction harness
  2: rope
  3: construction worker
  4: ladder
  5: scaffolding
  6: guardrail
  7: barricade
  8: open edge
  9: construction tool
  10: box
  11: ceiling
